on:
  push:
    branches:
      - main
name: release-please-main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-main
        with:
          release-type: node
          package-name: web
          token: ${{ secrets.PAT }}